### ISSUE TITLE
Not working w gnome-shell 3.38

### ISSUE THREAD

**Issue by tabascoz** [TheWeirdDev/somafm-radio-gnome-ext#22] opened 2020-11-14 14:24 UTC
Hi, the extension stopped working with 3.38; appreciate in advance if you could fix it! 

Please find the error:

 JS ERROR: Extension SomaFm-Radio@alireza6677.gmail.com: TypeError: meta is null
     _patchContainerClass/containerClass.prototype.child_set@resource:///org/gnome/shell/ui/environment.js:43:13
     _patchContainerClass/containerClass.prototype.add@resource:///org/gnome/shell/ui/environment.js:52:18
     createUi@/home/fernando/.local/share/gnome-shell/extensions/SomaFm-Radio@alireza6677.gmail.com/extension.js:141:18
    _init@/home/fernando/.local/share/gnome-shell/extensions/SomaFm-Radio@alireza6677.gmail.com/extension.js:79:14
    _init@/home/fernando/.local/share/gnome-shell/extensions/SomaFm-Radio@alireza6677.gmail.com/extension.js:284:17
     enable@/home/fernando/.local/share/gnome-shell/extensions/SomaFm-Radio@alireza6677.gmail.com/extension.js:337:14
    _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
    loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:348:26
   _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:586:18
   collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:28
   _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:565:19
   _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:595:18
   _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:626:18
   init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
   _initializeUI@resource:///org/gnome/shell/ui/main.js:269:22
   start@resource:///org/gnome/shell/ui/main.js:159:5
   @<main>:1:47

**Comment by TheWeirdDev** [comment] 2020-11-14 14:25
Duplicate of #21. Just install from this repository and it will work.

**Closed as completed by TheWeirdDev** 2020-11-14 14:25 UTC

**Comment by tabascoz** [comment] 2020-11-15 16:42
Thanks :)
